---
title: "Rezultati izbora"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)

source("R/Funkcije.R", encoding = "UTF-8")
```

R skripta za učitavanje DIP-ovih podataka o rezultatima glasovanja. [Izvor podataka](http://www.izbori.hr/arhiva-izbora/index.html#/app/home)

Trenutno je dostupna skripta za učitavanje podataka o lokalnim izborima 2017. godine.

Primjer korištenja:

```{r code, fig.height = 8}
xlsx_file_path_1krug <- "data/Lokalni/2017/rezultati1krug/ZUP_21/Excel/21.xlsx"
xlsx_file_path_2krug <- "data/Lokalni/2017/rezultati2krug/ZUP_021/Excel/21.xlsx"

krug_1 <- lokalni_izbori_procitaj(xlsx_file_path_1krug, drugi_krug = FALSE)
krug_2 <- lokalni_izbori_procitaj(xlsx_file_path_2krug, drugi_krug = TRUE)

# statistike prema birackim mjestima
krug_1$skupstina$header %>%
    sample_n(10) %>%
    kable(format = 'html') %>%
    kable_styling(bootstrap_options = "striped", font_size = 9)

# glasovi prema birackim mjestima
krug_1$skupstina$glasovi %>%
    sample_n(20) %>%
    kable(format = 'html') %>%
    kable_styling(bootstrap_options = "striped", font_size = 9)

# spajanje zaglavlja s glasovima po listama
krug_2$header %>%
    inner_join(
        krug_2$glasovi,
        by=c("bm_id"="bm_id","zupanija_id"="zupanija_id")
    ) %>%
    group_by(`Grad/općina`, `Adresa BM`, Lista) %>%
    summarise(
        Glasova = sum(Glasova),
        Vazecih_listica = sum(`Važeći listići`),
        Birackih_mjesta = n()
    ) %>%
    mutate(
        postotak = Glasova / Vazecih_listica
    ) %>%
    sample_n(1) %>%
    head(10) %>%
    kable(format = 'html') %>%
    kable_styling(bootstrap_options = "striped", font_size = 9)

# plot
krug_1$skupstina$header %>%
    inner_join(
        krug_1$skupstina$glasovi,
        by=c("bm_id"="bm_id","zupanija_id"="zupanija_id")
    ) %>%
    filter(grepl('Zagreb je naš', Lista, TRUE)) %>%
    group_by(`Grad/općina`, `Adresa BM`, Lista) %>%
    summarise(
        Glasova = sum(Glasova),
        Vazecih_listica = sum(`Važeći listići`),
        Birackih_mjesta = n()
    ) %>%
    mutate(
        postotak = Glasova / Vazecih_listica
    ) %>%
    arrange(-postotak) %>%
    head(40) %>%
    ggplot(aes(x = reorder(`Adresa BM`, postotak), y = postotak)) +
    geom_bar(stat='identity') +
    scale_y_continuous(labels = percent) +
    labs(
        x = 'Biracko mjesto', 
        y = 'postotak glasova',
        title = 'ZAGREB JE NAŠ!, NL, ORaH, RF, ZA GRAD'
    ) +
    coord_flip() +
    theme_gray()
```

